# Generated by Django 2.0.3 on 2018-08-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='main_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
