# Generated by Django 2.0.3 on 2018-08-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_companyinfo_main_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='tel',
            new_name='main_tel',
        ),
    ]
