# Generated by Django 2.0.3 on 2018-10-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180812_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('period', models.CharField(blank=True, max_length=200, null=True)),
                ('sum', models.CharField(blank=True, max_length=20, null=True)),
                ('vol', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
