# Generated by Django 2.0.3 on 2018-11-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_portfolioitemimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitemimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/item_img'),
        ),
    ]
