# Generated by Django 2.0.3 on 2018-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_portfolioitemimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitemimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
