# Generated by Django 2.0.3 on 2018-11-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181101_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='main_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
