# Generated by Django 2.0.3 on 2018-11-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_portfolioitemimagesbig_portfolioitemimagessmall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitemimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolioitemimagesbig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolioitemimagessmall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
