# Generated by Django 2.0.3 on 2018-11-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181103_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
